import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("builds the production-ready SEISMIC application", async () => {
  await access(new URL("../.next/BUILD_ID", import.meta.url));
  const [page, layout] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
  ]);
  assert.match(layout, /SEISMIC/);
  assert.match(layout, /<body suppressHydrationWarning>/);
  assert.match(layout, /clarity\.ms\/tag/);
  assert.match(layout, /y2tlzpkgbx/);
  assert.match(layout, /platform\.linkedin\.com\/badges\/js\/profile\.js/);
  assert.match(layout, /strategy="beforeInteractive"/);
  assert.match(page, /Interactive 3D/);
  assert.match(page, /Download PDF report/);
  assert.match(page, /Professional-use disclaimer/);
  assert.match(page, /RegionalSimulator/);
});

test("wires PDF, geolocated regional mapping, probabilistic forecasting, live USGS alerts, parameter help, and Vercel configuration", async () => {
  const [page, regional, forecast, forecastRoute, disclaimer, forecastLocales, disclaimerLocales, liveAlerts, emergencyKit, tooltip, i18n, i18nExtended, pdf, browserCompat, css, packageJson, vercel] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/RegionalSimulator.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/ForecastLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/api/forecast-catalog/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/components/DisclaimerPanel.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/forecast-locales.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/disclaimer-locales.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/components/LiveAlerts.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/EmergencyKit.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/ParameterTooltip.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/i18n.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/i18n-extended.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/pdf-report.mjs", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/browser-compat.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../vercel.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /createSeismicPdf/);
  assert.match(page, /Regional map/);
  assert.match(page, /SITE_CLASSES\[config\.siteClass\]\.amplification/);
  assert.match(page, /LocalizationRuntime/);
  assert.match(page, /className="language-switcher"/);
  assert.match(page, /className="topbar-tools"/);
  assert.match(page, /setLanguage\(nextLanguage\)/);
  assert.doesNotMatch(page, /window\.location\.reload/);
  assert.match(page, /RegionalSimulator language=\{language\}/);
  assert.match(page, /LiveAlerts language=\{language\}/);
  assert.match(page, /EmergencyKit language=\{language\}/);
  assert.match(page, /ForecastLab language=\{language\}/);
  assert.match(page, /DisclaimerPanel language=\{language\}/);
  assert.match(page, /helpTab === "disclaimer"/);
  assert.match(page, /className="skip-link"/);
  assert.match(page, /externalBrowserLaunchUrl\("https:\/\/www\.sismica\.pro\/"\)/);
  assert.match(page, /data-browser-handoff="true"/);
  assert.doesNotMatch(page, /Open SEISMIC in browser"\)<\/a>.*target="_blank"/);
  assert.match(page, /Accessibility options/);
  assert.match(page, /seismic-accessibility/);
  assert.match(page, /aria-current=\{appMode === "alerts"/);
  assert.match(page, /activeMode\?\.scrollIntoView\(\{ behavior: "auto", block: "nearest", inline: "center" \}\)/);
  assert.match(page, /running=\{running && !reduceMotion\}/);
  assert.match(page, /aria-live="polite" aria-atomic="true">Current structural response/);
  assert.match(page, /LI-profile-badge/);
  assert.match(page, /data-vanity="diego-avella"/);
  assert.match(page, /data-size="large"/);
  assert.match(page, /data-type="HORIZONTAL"/);
  assert.doesNotMatch(page, /badge-base__link LI-simple-link/);
  assert.doesNotMatch(page, /This link opens Diego’s LinkedIn profile in a new tab/);
  assert.match(page, /className="contact-github-link" href="https:\/\/github\.com\/mr-dap-lab\/seismic"/);
  assert.match(page, /window\.LIRenderAll/);
  assert.doesNotMatch(page, /className="linkedin-link"/);
  assert.match(page, />Emergency kit<\/button>/);
  assert.match(page, /appMode === "alerts"/);
  assert.match(page, /useState<"structure" \| "regional" \| "alerts" \| "forecast" \| "kit">\("alerts"\)/);
  assert.match(page, /Live alerts/);
  assert.ok(page.indexOf(">Live alerts</button>") < page.indexOf(">Regional map</button>"));
  assert.ok(page.indexOf(">Regional map</button>") < page.indexOf(">Forecast lab</button>"));
  assert.ok(page.indexOf(">Forecast lab</button>") < page.indexOf(">Structure lab</button>"));
  assert.ok(page.indexOf(">Regional map</button>") < page.indexOf(">Structure lab</button>"));
  assert.ok(page.indexOf(">Structure lab</button>") < page.indexOf(">Emergency kit</button>"));
  assert.match(i18n, /"en" \| "es" \| "fr" \| "yue" \| "hi" \| "ar" \| "pt" \| "ru" \| "ja" \| "it" \| "de"/);
  assert.match(i18n, /Español/);
  assert.match(i18n, /Français/);
  assert.match(i18n, /廣東話/);
  assert.match(i18n, /हिन्दी/);
  assert.match(i18n, /العربية/);
  assert.match(i18n, /Português/);
  assert.match(i18n, /Русский/);
  assert.match(i18n, /日本語/);
  assert.match(i18n, /Italiano/);
  assert.match(i18n, /Deutsch/);
  assert.equal((i18nExtended.match(/^  ".*": \[$/gm) ?? []).length, 418);
  assert.match(i18nExtended, /Kit de emergência/);
  assert.match(i18nExtended, /Аварийный комплект/);
  assert.match(i18nExtended, /緊急キット/);
  assert.match(i18nExtended, /Kit di emergenza/);
  assert.match(i18nExtended, /Notfallset/);
  assert.match(i18n, /Emergency kit checklist/);
  assert.match(i18n, /Kit de emergencia/);
  assert.match(i18n, /language === "ar" \? "rtl" : "ltr"/);
  assert.match(pdf, /jspdf-autotable/);
  assert.match(pdf, /IMPORTANT PROFESSIONAL-USE DISCLAIMER/);
  assert.match(pdf, /createRegionalPdf/);
  assert.match(pdf, /enableUnicodeText/);
  assert.match(pdf, /t\("STRUCTURAL RESPONSE REPORT"\)/);
  assert.match(pdf, /LANGUAGE_LOCALES/);
  assert.match(pdf, /Map data © OpenStreetMap contributors/);
  assert.match(browserCompat, /intent:\/\//);
  assert.match(browserCompat, /android\.intent\.action\.VIEW/);
  assert.match(browserCompat, /android\.intent\.category\.BROWSABLE/);
  assert.match(browserCompat, /x-safari-/);
  assert.match(browserCompat, /S\.browser_fallback_url=/);
  assert.match(regional, /maplibre-gl/);
  assert.match(regional, /translateText, type Language/);
  assert.match(regional, /const MAP_STYLE: StyleSpecification/);
  assert.match(regional, /tile\.openstreetmap\.org\/\{z\}\/\{x\}\/\{y\}\.png/);
  assert.match(regional, /"raster-fade-duration": 0/);
  assert.match(regional, /navigator\.geolocation\.getCurrentPosition/);
  assert.match(regional, /fetch\(`\/api\/geocode\?/);
  assert.match(regional, /function impactRadii/);
  assert.match(regional, /function updateImpactLayers/);
  assert.match(regional, /captureImpactMap\(map, impactOverlayRef\.current\)/);
  assert.match(regional, /createRegionalPdf/);
  assert.doesNotMatch(regional, /3D|fill-extrusion|OpenFreeMap|openfreemap|preloader/);
  assert.match(regional, /placingEpicenterRef/);
  assert.match(regional, /userSelectedLocationRef/);
  assert.match(regional, /updateImpactLayers\(map, selectedCenter, radiiRef\.current\)/);
  assert.match(regional, /Set epicenter/);
  assert.match(regional, /className="report-button has-tooltip tooltip-top"/);
  assert.ok(regional.indexOf("Set epicenter") < regional.indexOf("Find a city or place"));
  assert.ok(regional.indexOf("Find a city or place") < regional.indexOf("Latitude"));
  assert.ok(regional.indexOf("Representative site class") < regional.indexOf("Latitude"));
  assert.match(regional, /\{t\("Class"\)\} \{site\} — \{t\(SITE_CLASS_NAMES\[site\]\)\}/);
  assert.match(regional, /resetRegional/);
  assert.match(regional, /fillOpacity="0\.18"/);
  assert.match(regional, /IMPACT_ZONES\.forEach/);
  assert.match(regional, /updateImpactLayers\(map, center, radii\)/);
  assert.match(regional, /projectImpactGeometry/);
  assert.match(regional, /regional-impact-overlay/);
  assert.match(regional, /id="regional-map-description"/);
  assert.match(regional, /aria-live="polite" aria-atomic="true">Regional scenario result/);
  assert.match(regional, /map\.triggerRepaint\(\)/);
  assert.match(liveAlerts, /earthquake\.usgs\.gov\/earthquakes\/feed\/v1\.0\/summary\/all_day\.geojson/);
  assert.match(liveAlerts, /earthquake\.usgs\.gov\/fdsnws\/event\/1\/query/);
  assert.match(liveAlerts, /"48hours": "Past 48 hours"/);
  assert.match(liveAlerts, /"72hours": "Past 72 hours"/);
  assert.match(liveAlerts, /pt: "pt-BR"/);
  assert.match(liveAlerts, /ru: "ru-RU"/);
  assert.match(liveAlerts, /ja: "ja-JP"/);
  assert.match(liveAlerts, /it: "it-IT"/);
  assert.match(liveAlerts, /de: "de-DE"/);
  assert.match(liveAlerts, /const WORLD_ZOOM = 1\.45/);
  assert.match(liveAlerts, /zoom: WORLD_ZOOM/);
  assert.match(liveAlerts, /setProjection\(\{ type: "globe" \}\)/);
  assert.match(liveAlerts, /window\.setInterval\(\(\) => void refresh\(\), 60_000\)/);
  assert.match(liveAlerts, /Notification\.requestPermission\(\)/);
  assert.match(liveAlerts, /new Notification/);
  assert.match(liveAlerts, /seenIdsRef/);
  assert.match(liveAlerts, /cache: "no-store"/);
  assert.match(liveAlerts, /USGS data is preliminary and may be revised/);
  assert.match(liveAlerts, /Data source: U\.S\. Geological Survey/);
  assert.match(liveAlerts, /from "maplibre-gl"/);
  assert.match(liveAlerts, /const WORLD_MAP_STYLE: StyleSpecification/);
  assert.match(liveAlerts, /tile\.openstreetmap\.org\/\{z\}\/\{x\}\/\{y\}\.png/);
  assert.match(liveAlerts, /function earthquakePoints/);
  assert.match(liveAlerts, /id: "live-earthquake-points"/);
  assert.match(liveAlerts, /new Marker/);
  assert.match(liveAlerts, /alerts-earthquake-marker/);
  assert.match(liveAlerts, /markerButton\.style\.width = "44px"/);
  assert.match(liveAlerts, /role="status" aria-live="polite" aria-atomic="true"/);
  assert.match(liveAlerts, /WorldEarthquakeMap events=\{filteredEvents\}/);
  assert.match(liveAlerts, /Worldwide earthquake map/);
  assert.match(forecastRoute, /earthquake\.usgs\.gov\/fdsnws\/event\/1\/query/);
  assert.match(forecastRoute, /minmagnitude: "5"/);
  assert.match(forecastRoute, /revalidate: 3600/);
  assert.match(forecast, /const ETAS = \{ alpha: 0\.8, c: 0\.05, p: 1\.1, q: 1\.5/);
  assert.match(forecast, /1 - Math\.exp\(-expected\)/);
  assert.match(forecast, /10 \*\* \(-\(targetMagnitude - catalog\.minimumCatalogMagnitude\)\)/);
  assert.match(forecast, /REMOTE_STRESS_WEIGHTS/);
  assert.match(forecast, /TIDAL_WEIGHTS/);
  assert.match(forecast, /EARTH_CYCLE_WEIGHTS/);
  assert.match(forecast, /SHOW_EXPERIMENTAL_FORECAST_CONTROLS = false/);
  assert.match(forecast, /earthCycleEnvelope/);
  assert.match(forecast, /setRemoteStressWeight/);
  assert.match(forecast, /setTidalWeight/);
  assert.match(forecast, /setEarthCycleWeight/);
  assert.match(forecast, /remoteShare\[index\] \* remoteStressWeight/);
  assert.match(forecast, /tidalWeight \* tide\.envelope/);
  assert.match(forecast, /earthCycleWeight \* earthCycle\.envelope/);
  assert.match(forecast, /onClick=\{resetParameters\}/);
  assert.doesNotMatch(forecast, /remoteEnabled|tideEnabled/);
  assert.match(forecast, /No exact earthquake prediction/);
  assert.match(forecast, /cannot predict the exact next earthquake/);
  assert.match(forecast, /USGS on earthquake prediction/);
  assert.match(forecast, /features: cells\.map/);
  assert.doesNotMatch(forecast, /features: cells\.slice/);
  assert.match(forecast, /FORECAST_COVERAGE_REGIONS/);
  assert.match(forecast, /forecastMarkerCells\(cells\)/);
  assert.match(forecast, /dataset\.coverageRegion = forecastCoverageRegion/);
  assert.doesNotMatch(forecast, /markersRef\.current = cells\.slice/);
  assert.match(forecast, /event\.magnitude >= catalog\.minimumCatalogMagnitude/);
  assert.doesNotMatch(forecast, /magnitudeSeedThreshold/);
  assert.match(forecast, /Math\.sqrt\(cell\.probability \/ 0\.5\)/);
  assert.match(forecast, /new Popup/);
  assert.match(forecast, /Baseline spatial share/);
  assert.match(forecastLocales, /FORECAST_TRANSLATION_SOURCE_COUNT = sources\.length/);
  assert.match(forecastLocales, /La magnitud mínima que se pronostica/);
  assert.match(forecastLocales, /予測対象の最小マグニチュード/);
  assert.match(disclaimer, /This software does not predict earthquakes/);
  assert.match(disclaimer, /this application is a merely an academic exercise/);
  assert.doesNotMatch(disclaimer, /It was prepared by an AI assistant, not an attorney/);
  assert.match(disclaimer, /no component of that toolkit was validated against the live USGS catalog/i);
  assert.match(disclaimerLocales, /DISCLAIMER_TRANSLATION_SOURCE_COUNT = sources\.length/);
  assert.match(disclaimerLocales, /Este software no predice terremotos/);
  assert.match(disclaimerLocales, /このソフトウェアは地震を予知しません/);
  assert.match(emergencyKit, /const STORAGE_KEY = "seismic-emergency-kit"/);
  assert.match(emergencyKit, /Emergency kit checklist/);
  assert.match(emergencyKit, /KIT_CATEGORIES/);
  assert.match(emergencyKit, /householdSize \* planningDays \* 3\.8/);
  assert.match(emergencyKit, /redcross\.org/);
  assert.match(emergencyKit, /role="status" aria-live="polite"/);
  assert.match(tooltip, /role="tooltip"/);
  assert.match(tooltip, /aria-describedby/);
  assert.match(css, /\.parameter-tooltip-bubble/);
  assert.match(css, /\.regional-search/);
  assert.match(css, /\.regional-map\.placing-epicenter \.maplibregl-canvas \{ cursor: crosshair/);
  assert.match(css, /\.epicenter-tool/);
  assert.match(css, /\.impact-ring-high/);
  assert.match(css, /\.report-button/);
  assert.match(css, /\.language-switcher/);
  assert.match(css, /min-width: 148px/);
  assert.match(css, /\.topbar-tools/);
  assert.match(css, /grid-template-columns: minmax\(230px, 1fr\) auto minmax\(320px, 1fr\)/);
  assert.match(css, /@media \(min-width: 761px\) and \(max-width: 1480px\)/);
  assert.match(css, /\.live-alerts-shell/);
  assert.match(css, /\.forecast-shell/);
  assert.match(css, /\.forecast-warning/);
  assert.match(css, /\.forecast-map/);
  assert.match(css, /\.forecast-popup/);
  assert.match(css, /\.forecast-weight-field\s*\{[^}]*flex-direction:\s*column/s);
  assert.match(css, /\.forecast-actions\s*\{[^}]*flex-direction:\s*column/s);
  assert.match(css, /\.forecast-reset/);
  assert.match(css, /\.disclaimer-panel/);
  assert.match(css, /\.alerts-event-list/);
  assert.match(css, /\.alerts-world-map-section/);
  assert.match(css, /\.alerts-world-map-stage/);
  assert.match(css, /\.alerts-world-map\.maplibregl-map\s*\{[^}]*position:\s*absolute;[^}]*height:\s*100%/s);
  assert.match(css, /\.alerts-earthquake-marker/);
  assert.match(css, /\.alerts-map-selection/);
  assert.match(css, /\.kit-checklist label\s*\{[^}]*font-size:\s*0\.75rem/s);
  assert.match(css, /\.emergency-kit-shell/);
  assert.match(emergencyKit, /className="kit-hero-band"/);
  assert.match(emergencyKit, /className="kit-body"/);
  assert.match(css, /\.kit-hero h1\s*\{[^}]*clamp\(32px, 3vw, 44px\)/s);
  assert.match(css, /\.linkedin-badge-shell \.LI-profile-badge\s*\{[^}]*justify-content:\s*center;[^}]*margin:\s*0 auto/s);
  assert.match(css, /\.contact-github-link\s*\{[^}]*margin:\s*18px auto 0/s);
  assert.match(css, /\.webview-notice/);
  assert.match(css, /env\(safe-area-inset-top\)/);
  assert.match(css, /input, select, textarea \{ font-size: 16px !important/);
  assert.match(page, /isEmbeddedSocialBrowser/);
  assert.match(page, /preparePdfDelivery/);
  assert.match(pdf, /navigator\.share/);
  assert.match(pdf, /URL\.createObjectURL\(blob\)/);
  assert.match(regional, /fetch\(`\/api\/geocode\?/);
  assert.match(css, /\.kit-category-grid/);
  assert.match(css, /\.kit-progress-ring/);
  assert.match(css, /\.kit-planning-bar > label\s*\{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto/s);
  assert.match(css, /\.kit-planning-bar > label > span\s*\{[^}]*align-self:\s*end/s);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.control-panel\s*\{[^}]*max-width:\s*100vw;[^}]*overflow-x:\s*clip/s);
  assert.match(css, /\.tab-list \.tooltip-bubble\s*\{[^}]*display:\s*none/s);
  assert.match(css, /\.panel-title-row \.text-button\s*\{[^}]*max-width:\s*45%;[^}]*overflow-wrap:\s*anywhere/s);
  assert.match(css, /\.mode-nav button \{ flex: 1; min-width: 0/);
  assert.match(css, /\.select-control select, \.regional-field select \{ min-height: 44px; font-size: 0\.875rem/);
  assert.match(css, /html\[data-text-size="large"\]/);
  assert.match(css, /\.a11y-high-contrast/);
  assert.match(css, /\.a11y-reduce-motion/);
  assert.match(css, /\.skip-link/);
  assert.match(css, /html\[dir="rtl"\]/);
  assert.doesNotMatch(css, /\.regional-report/);
  assert.match(css, /\.regional-shell\s*\{/);
  assert.match(packageJson, /"jspdf"/);
  assert.match(packageJson, /"maplibre-gl"/);
  assert.doesNotMatch(packageJson, /googlemaps|leaflet/);
  assert.match(vercel, /"framework": "nextjs"/);
});
